# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.cache/wt [current_project]
set_property parent.project_path D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/memfile.dat
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/io.dat
}
read_verilog -library xil_defaultlib -sv {
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/ALU_32bit.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/MIPS_Single_Cycle.srcs/Hex7Seg.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/IO.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/MemoryDecoder.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/aludec.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/controller.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/datapath.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/dmux.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/flopenr.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/flopr.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/instrDataMemory.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/maindec.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/mips.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/mux2.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/mux4.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/regfile.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/signext.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/sl2.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/MIPS_Single_Cycle.srcs/x7seg.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/imports/new/zeroext.sv
  D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/sources_1/new/MipsIO_Top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/constrs_1/imports/VivadoProject/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/Development/VivadoProject/MulticycleProcessor/MulticycleProcessor.srcs/constrs_1/imports/VivadoProject/Nexys4DDR_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MipsIO_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MipsIO_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MipsIO_Top_utilization_synth.rpt -pb MipsIO_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
